name: parse_server_sdk_flutter
description: Flutter plugin for Parse Server, (https://parseplatform.org), (https://back4app.com)
version: 5.0.0
homepage: https://github.com/parse-community/Parse-SDK-Flutter

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  parse_server_sdk: ^5.0.0

  # Networking
  dio: ^5.0.1
  connectivity_plus: ^3.0.3 # only used in the flutter part

  #Database
  shared_preferences: ^2.0.18 # only used in the flutter part

  # Utils
  path_provider: ^2.0.13 # only used in the flutter part
  package_info_plus: ^3.0.3 # only used in the flutter part
  sembast: ^3.4.0+6
  sembast_web: ^2.1.0+4
  path: ^1.8.2 # required for transitive use only

dependency_overrides:
  # Override to local mono-repo path so devs can test this repo
  # against changes that they're making to other mono-repo packages.
  parse_server_sdk:
    path: ../dart


dev_dependencies:
  flutter_lints: ^2.0.1
  # Testing
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  path_provider_platform_interface: ^2.0.6
  plugin_platform_interface: ^2.1.4



